export const subscribeHtml = [
  '<div class="subscribe-container">',
    '<div class="subscribe-heading">§subscribe-heading§</div>',
    '<div class="subscribe-subtext">§subscribe-subtext§</div>',
    '<div class="subscribe-form-row">',
      '<input class="subscribe-input" type="email" placeholder="§subscribe-input§">',
      '<button class="subscribe-button" onclick="bsSubscribe(this,\'§projectId§\')">§subscribe-button§</button>',
    '</div>',
  '</div>',
  '<script>',
  'if(!window.bsSubscribe){window.bsSubscribe=function(btn,id){',
  'var inp=btn.previousElementSibling;',
  'if(!inp.value||!inp.value.includes(\'@\')){inp.style.outline=\'2px solid red\';return;}',
  'inp.style.outline=\'\';btn.disabled=true;',
  'fetch(\'/restaurants/newsletter/subscribe\',{method:\'POST\',headers:{\'Content-Type\':\'application/json\'},body:JSON.stringify({email:inp.value,projectId:id})})',
  '.then(function(r){return r.json();})',
  '.then(function(d){btn.textContent=d.success?\'Subscribed!\':d.message;})',
  '.catch(function(){btn.textContent=\'Try again\';btn.disabled=false;});}}',
  '<\/script>',
].join('');
